name: Cypress Tests

on:
  push:
    branches: [ main, develop, workflow-test ] # needed?
  pull_request:
    branches: [ main, develop, workflow-test ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 14.x ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          build: yarn build
          start: yarn start
